version: "3"
services:
  db:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "1"
      POSTGRES_DB: "testdb"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
